name: C# Build

on: 
  push:
    branches:
        master # Runs on every push to the main branch
  pull_request:
    branches:
        main # Runs on every pull request to main

jobs:
  build:
    runs-on: windows-latest # Use the latest window runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore --configuration Release #Builds the project

      
      
