name: .NET CI Workflow

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: POEPart1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore

      - name: Run Test
        run: dotnet test --no-build
--verbosity normal

      
